class Autogenerated {
  String? _author;
  String? _datePublished;
  String? _timePublished;
  String? _content;

  Autogenerated({
    String? author,
    String? datePublished,
    String? timePublished,
    String? content
  }) {
    if (author != null) {
      this._author = author;
    }
    if (datePublished != null) {
      this._datePublished = datePublished;
    }
    if (timePublished != null) {
      this._timePublished = timePublished;
    }
    if (content != null) {
      this._content = content;
    }
  }

  String? get author => _author;
  set author(String? author) => _author = author;
  String? get datePublished => _datePublished;
  set datePublished(String? datePublished) => _datePublished = datePublished;
  String? get timePublished => _timePublished;
  set timePublished(String? timePublished) => _timePublished = timePublished;
  String? get content => _content;
  set content(String? content) => _content = content;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _author = json['author'];
    _datePublished = json['date_published'];
    _timePublished = json['time_published'];
    _content = json['content'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['author'] = this._author;
    data['date_published'] = this._datePublished;
    data['time_published'] = this._timePublished;
    data['content'] = this._content;
    return data;
  }
}